services:
  redis:
    image: redis:7.2
    container_name: redis_container
    restart: no
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - ./scripts/entrypoint.sh:/usr/local/bin/entrypoint.sh
    entrypoint: [ "sh", "/usr/local/bin/entrypoint.sh" ]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    tty: true
    stdin_open: true

  postgres:
    image: postgres:17.4
    container_name: postgres_container
    restart: no
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U monitoring_user -d monitoring_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    tty: true
    stdin_open: true